1] CURSOR PROGRAM FOR ELECTRICITY BILL CALCULATION

create table Electricity049 (Name varchar2(15), Prev_Reading number(5), Curr_Reading number(5));
INSERT INTO Electricity049 VALUES ('Shushrut Kumar', 2590, 5891);
INSERT INTO Electricity049 VALUES ('Viren Parmar', 7555, 10210);
INSERT INTO Electricity049 VALUES ('Vidhi Rai', 8190, 11203);

set serveroutput on;
DECLARE
CURSOR bill
IS
SELECT * FROM Electricity049;
ROW_ELECTRICITY ELECTRICITY049%ROWTYPE;
AMOUNT NUMBER(9,2);
BEGIN
OPEN bill;
LOOP
FETCH bill INTO ROW_ELECTRICITY;
EXIT WHEN bill%NOTFOUND;
AMOUNT := ( ROW_ELECTRICITY.CURR_READING - ROW_ELECTRICITY.PREV_READING ) * 5;
DBMS_OUTPUT.PUT_LINE('BILL FOR ' || ROW_ELECTRICITY.NAME || ' is Rs ' || AMOUNT);
END LOOP;
CLOSE bill;
END;
/

2] CURSOR PROGRAM FOR STUDENT GRADE CALCULATION

create table STUDENT049 (Name varchar(20), Maths number(3), Science number(3));
INSERT INTO STUDENT049 VALUES ('Shushrut Kumar', 79, 84);
INSERT INTO STUDENT049 VALUES ('Viren Parmar', 99, 88);
INSERT INTO STUDENT049 VALUES ('Sachin Tilokani', 34, 65);
INSERT INTO STUDENT049 VALUES ('Neel Thakar', 67, 55);
INSERT INTO STUDENT049 VALUES ('Param Shah', 49, 46);

set serveroutput on;
DECLARE
CURSOR grade
IS
SELECT * FROM STUDENT049;
STUDENT_ROW STUDENT049%ROWTYPE;
BEGIN
OPEN grade;
LOOP
FETCH grade INTO STUDENT_ROW;
EXIT WHEN grade%NOTFOUND;
IF (STUDENT_ROW.MATHS + STUDENT_ROW.SCIENCE) > 100 THEN
DBMS_OUTPUT.PUT_LINE(STUDENT_ROW.NAME || ' has achieved grade PASS with total marks = ' || (STUDENT_ROW.MATHS + STUDENT_ROW.SCIENCE));
ELSE
DBMS_OUTPUT.PUT_LINE(STUDENT_ROW.NAME || ' has achieved grade FAIL with total marks = ' || (STUDENT_ROW.MATHS + STUDENT_ROW.SCIENCE));
END IF;
END LOOP;
CLOSE grade;
END;
/